#######################################
# Dockerfile for Apache-PHP
# PHP 7.3
# Apache 2.4
# MySQL 8.0
# phpMyAdmin
# Author: Shiina
# Date: 2022-12-12
#######################################

version: '3.3'
services:
    www:
        container_name: php73
        build: 
          context: ./apache-php
          dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "${HOST_HTTP_PORT}:80"
            - "${HOST_HTTPS_PORT}:443"
        volumes:
            - ${APACHE_WWW_VOLUME}:/var/www/html/
            - ${APACHE_LOG_VOLUME}:/var/log/apache2
    db:
        container_name: mysql8
        image: mysql:8.0
        command: 
            --default-authentication-plugin=mysql_native_password
            --init-file /data/application/init.sql
        restart: always
        volumes:
            - ${MYSQL_VOLUME}:/data/application/init.sql
        environment:
            MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE:registration
            MYSQL_USER:devuser
            MYSQL_PASSWORD:devpass
        ports:
            - "${HOST_MYSQL_PORT}:3306"
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        environment:
            - PMA_ARBITRARY:1
            - PMA_HOST:mysql
            - MYSQL_USERNAME:root
            - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
        ports:
            - "${HOST_PHPMYADM_PORT}:80"
        depends_on:
            - db
